[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pytincture_example"
version = "0.1.2"
description = "UI Example"
readme = "README.md"
license = { text = "GNU General Public License v2.0" }
authors = [
    { name = "Your Name", email = "schapman1974@gmail.com" }
]
dependencies = [
    "pytincture[password]==1.0.0rc1",
    "dhxpyt==0.9.16",
]
requires-python = ">=3.13"

[project.optional-dependencies]
browser-test = ["playwright>=1.58,<2"]
load-test = ["httpx>=0.28,<1"]

[project.urls]
Homepage = "https://github.com/pytincture/pytincture_example"

[tool.setuptools.packages]
find = {}
