name: Publish Docker image to Docker Hub

on:
  workflow_dispatch:
  release:
    types: [created]
    branches:
      - main
    tags:
      - '*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep -Po '(?<=version = ")[^"]*' pyproject.toml)
          VERSION_NO_DOTS=${VERSION//./}
          echo "::set-output name=version::${VERSION_NO_DOTS}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: pytincture/pytincture
      
      - name: Build and push Docker image for multiple platforms
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            pytincture/pytincture:example${{ steps.get_version.outputs.version }}
            pytincture/pytincture:latest
          labels: ${{ steps.meta.outputs.labels }}
